"""
Script: phase5__generate__replit_boundary.py
Intent: snapshot
Generates Replit prototyping boundary JSON files for Phase 5
"""

import json
from datetime import datetime, timezone
from pathlib import Path

BASE_DIR = Path(__file__).parent.parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Output files
OUTPUT_ALLOWED = DATA_DIR / "replit_allowed.json"
OUTPUT_FORBIDDEN = DATA_DIR / "replit_forbidden.json"
OUTPUT_IMPORT = DATA_DIR / "replit_import_path.json"
OUTPUT_DISPOSAL = DATA_DIR / "replit_disposal.json"


def generate_replit_allowed():
    """Define Replit allowed activities"""
    allowed = {
        "_meta": {
            "generated_at": datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
            "phase": 5
        },
        "allowed_activities": [
            {
                "activity": "UI Mockups",
                "description": "HTML/CSS/JS prototypes for dashboard sections",
                "purpose": "Rapid prototyping and experimentation",
                "constraints": "Must be disposable, no production dependencies"
            },
            {
                "activity": "API Mockups",
                "description": "FastAPI endpoint prototypes",
                "purpose": "Test API designs before implementation",
                "constraints": "No canonical logic, mock data only"
            },
            {
                "activity": "Data Transforms",
                "description": "JSON transformation experiments",
                "purpose": "Test data transformation logic",
                "constraints": "No persistence, temporary outputs only"
            },
            {
                "activity": "Visualization Experiments",
                "description": "Chart/graph prototypes",
                "purpose": "Explore visualization options",
                "constraints": "No production dependencies"
            }
        ]
    }
    return allowed


def generate_replit_forbidden():
    """Define Replit forbidden activities"""
    forbidden = {
        "_meta": {
            "generated_at": datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
            "phase": 5
        },
        "forbidden_activities": [
            {
                "activity": "Canonical Logic",
                "description": "No production business logic",
                "rationale": "Replit is for prototyping only, not production code"
            },
            {
                "activity": "Secrets",
                "description": "No API keys, credentials, sensitive data",
                "rationale": "Security: Replit outputs are disposable and not secure"
            },
            {
                "activity": "Merges",
                "description": "No direct GitHub merges from Replit",
                "rationale": "All code must be reviewed in Cursor before merging"
            },
            {
                "activity": "State Modification",
                "description": "No legislative state changes",
                "rationale": "State changes require human approval and proper workflow"
            },
            {
                "activity": "Production Artifacts",
                "description": "No generation of production artifact files",
                "rationale": "Artifacts must be generated by agents following proper workflow"
            }
        ]
    }
    return forbidden


def generate_replit_import_path():
    """Define import path from Replit to Cursor"""
    import_path = {
        "_meta": {
            "generated_at": datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
            "phase": 5
        },
        "import_process": {
            "step_1": {
                "action": "Manual Import",
                "description": "User copies Replit code into Cursor workspace",
                "method": "Copy-paste or file transfer",
                "location": "Temporary directory in Cursor workspace"
            },
            "step_2": {
                "action": "Review Required",
                "description": "All Replit imports require human review",
                "checks": [
                    "Code follows Cursor standards",
                    "No hardcoded secrets",
                    "No production dependencies",
                    "Proper error handling"
                ]
            },
            "step_3": {
                "action": "Refactoring Required",
                "description": "Replit code must be refactored to match Cursor standards",
                "refactoring_tasks": [
                    "Add proper imports and dependencies",
                    "Follow agent structure conventions",
                    "Add proper error handling",
                    "Add logging and audit trails",
                    "Update file paths to match Cursor structure"
                ]
            },
            "step_4": {
                "action": "Integration",
                "description": "Integrated code goes through normal review process",
                "process": "Follow standard agent/script review and approval workflow"
            }
        },
        "import_rules": {
            "no_automated_import": True,
            "human_review_mandatory": True,
            "refactoring_mandatory": True,
            "test_before_integration": True
        }
    }
    return import_path


def generate_replit_disposal():
    """Define Replit disposal rules"""
    disposal = {
        "_meta": {
            "generated_at": datetime.now(timezone.utc).isoformat().replace('+00:00', 'Z'),
            "phase": 5
        },
        "disposal_rules": {
            "disposable": {
                "description": "All Replit outputs are considered disposable",
                "rationale": "Replit is for experimentation, not persistence"
            },
            "no_persistence": {
                "description": "Replit prototypes are not persisted to GitHub",
                "rationale": "Only reviewed and approved code enters version control"
            },
            "no_dependencies": {
                "description": "Cursor code must not depend on Replit outputs",
                "rationale": "Replit outputs are temporary and may be deleted"
            },
            "cleanup": {
                "description": "Replit prototypes can be deleted at any time",
                "rationale": "No production dependencies on disposable prototypes"
            }
        },
        "disposal_process": {
            "when": "After code is imported and integrated into Cursor",
            "how": "Delete Replit project or archive",
            "backup": "No backup required (code is in Cursor)",
            "notification": "Optional: notify if prototype had useful patterns"
        }
    }
    return disposal


def main():
    """Generate all Phase 5 output files"""
    # Replit allowed
    allowed = generate_replit_allowed()
    OUTPUT_ALLOWED.write_text(json.dumps(allowed, indent=2), encoding='utf-8')
    print(f"Generated {OUTPUT_ALLOWED.name}")
    
    # Replit forbidden
    forbidden = generate_replit_forbidden()
    OUTPUT_FORBIDDEN.write_text(json.dumps(forbidden, indent=2), encoding='utf-8')
    print(f"Generated {OUTPUT_FORBIDDEN.name}")
    
    # Import path
    import_path = generate_replit_import_path()
    OUTPUT_IMPORT.write_text(json.dumps(import_path, indent=2), encoding='utf-8')
    print(f"Generated {OUTPUT_IMPORT.name}")
    
    # Disposal
    disposal = generate_replit_disposal()
    OUTPUT_DISPOSAL.write_text(json.dumps(disposal, indent=2), encoding='utf-8')
    print(f"Generated {OUTPUT_DISPOSAL.name}")
    
    print("Phase 5 outputs generated successfully")


if __name__ == "__main__":
    main()
